import type { Metadata } from "next";
import { Almarai, Black_Han_Sans } from 'next/font/google';
import "./globals.css";
import Navbar from "../components/Navbar";

const almarai = Almarai({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  display: 'swap',
  variable: '--font-almarai',
});

const blackHanSans = Black_Han_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-black-han-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${almarai.variable} ${blackHanSans.variable}`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}